[package]
name = "versust"
version = "1.0.0"
edition = "2024"

description = "A Rust library for structured concurrency patterns."
license = "MIT OR Apache-2.0"
repository = "https://github.com/CookieHCl/versust"
readme = "README.md"

exclude = [".github/*"]
